version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - '3308:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      - MYSQL_DATABASE=test
